# ***Student_Name=Nirmal Rawal***
# ***Student_Id =2358113***

# 4 TO - DO - Task
Please complete all the problem listed below.
# 4.1 Exercise on Functions:
Task - 1:
Create a Python program that converts between different units of measurement.
• The program should:
1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).
2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.
4. Handle potential errors, such as invalid input or unsupported conversion types.
• Requirements:
1. Functions: Define at least one function to perform the conversion.
2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).
3. User Input: Prompt the user to select the conversion type and input the value.
4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and
return value.


# • Conversion Options:
1. Length:
– Convert meters (m) to feet (ft).
– Convert feet (ft) to meters (m).
2. Weight:
– Convert kilograms (kg) to pounds (lbs).
– Convert pounds (lbs) to kilograms (kg).
3. Volume:
– Convert liters (L) to gallons (gal).
– Convert gallons (gal) to liters (L).

In [ ]:
def main():

    print("Welcome to the Unit Converter!")
    print("Please select the type of conversion:")
    print("1. Length")
    print("2. Weight")
    print("3. Volume")

    try:
        # Prompt user to select conversion type
        conversion_type = int(input("Enter the number corresponding to your choice: "))

        if conversion_type not in [1, 2, 3]:
            print("Invalid choice. Please enter a valid number.")
            return

        # Prompt user to input the value to be converted
        value = float(input("Enter the value to be converted: "))

        if conversion_type == 1:
            # Length conversion
            print("Select length conversion:")
            print("1. Meters (m) to Feet (ft)")
            print("2. Feet (ft) to Meters (m)")
            length_choice = int(input("Enter your choice: "))

            if length_choice == 1:
                result = convert_length(value, 'm', 'ft')
                print(f"{value} meters is equal to {result:.2f} feet.")
            elif length_choice == 2:
                result = convert_length(value, 'ft', 'm')
                print(f"{value} feet is equal to {result:.2f} meters.")
            else:
                print("Invalid choice for length conversion.")

        elif conversion_type == 2:
            # Weight conversion
            print("Select weight conversion:")
            print("1. Kilograms (kg) to Pounds (lbs)")
            print("2. Pounds (lbs) to Kilograms (kg)")
            weight_choice = int(input("Enter your choice: "))

            if weight_choice == 1:
                result = convert_weight(value, 'kg', 'lbs')
                print(f"{value} kilograms is equal to {result:.2f} pounds.")
            elif weight_choice == 2:
                result = convert_weight(value, 'lbs', 'kg')
                print(f"{value} pounds is equal to {result:.2f} kilograms.")
            else:
                print("Invalid choice for weight conversion.")

        elif conversion_type == 3:
            # Volume conversion
            print("Select volume conversion:")
            print("1. Liters (L) to Gallons (gal)")
            print("2. Gallons (gal) to Liters (L)")
            volume_choice = int(input("Enter your choice: "))

            if volume_choice == 1:
                result = convert_volume(value, 'L', 'gal')
                print(f"{value} liters is equal to {result:.2f} gallons.")
            elif volume_choice == 2:
                result = convert_volume(value, 'gal', 'L')
                print(f"{value} gallons is equal to {result:.2f} liters.")
            else:
                print("Invalid choice for volume conversion.")

    except ValueError as e:
        # Handle invalid input (non-numeric values)
        print(f"Error: {e}. Please enter a valid number.")


def convert_length(value, from_unit, to_unit):

    if from_unit == 'm' and to_unit == 'ft':
        return value * 3.28084
    elif from_unit == 'ft' and to_unit == 'm':
        return value / 3.28084
    else:
        raise ValueError("Unsupported length conversion units.")


def convert_weight(value, from_unit, to_unit):

    if from_unit == 'kg' and to_unit == 'lbs':
        return value * 2.20462
    elif from_unit == 'lbs' and to_unit == 'kg':
        return value / 2.20462
    else:
        raise ValueError("Unsupported weight conversion units.")


def convert_volume(value, from_unit, to_unit):

    if from_unit == 'L' and to_unit == 'gal':
        return value * 0.264172
    elif from_unit == 'gal' and to_unit == 'L':
        return value / 0.264172
    else:
        raise ValueError("Unsupported volume conversion units.")


if __name__ == "__main__":
    main()

Welcome to the Unit Converter!
Please select the type of conversion:
1. Length
2. Weight
3. Volume
Enter the number corresponding to your choice: 2
Enter the value to be converted: 78
Select weight conversion:
1. Kilograms (kg) to Pounds (lbs)
2. Pounds (lbs) to Kilograms (kg)
Enter your choice: 1
78.0 kilograms is equal to 171.96 pounds.


# Task - 2:
# Create a Python program that performs various mathematical operations on a list of numbers.
• The Program should:
1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum
of the numbers).
2. Ask the user to input a list of numbers (separated by spaces).

18



3. Perform the selected operation and display the result.
4. Handle potential errors, such as invalid input or empty lists.
• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, mini-
mum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or
empty lists).
3. User Input: Prompt the user to select the operation and input the list of numbers.
4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and
return value.

In [ ]:
def calculate_sum(numbers):
    return sum(numbers)


def calculate_average(numbers):
    return sum(numbers) / len(numbers)


def find_maximum(numbers):
    return max(numbers)


def find_minimum(numbers):
    return min(numbers)


def main():
    """
    Main function to handle user input and perform mathematical operations.
    """
    print("Welcome to the Math Operations Program!")
    print("Please select an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        # Prompt user to select an operation
        operation = int(input("Enter the number corresponding to your choice: "))

        if operation not in [1, 2, 3, 4]:
            print("Invalid choice. Please select a number between 1 and 4.")
            return

        # Prompt user to input a list of numbers
        user_input = input("Enter a list of numbers separated by commas: ").strip()

        # Check if the user input is empty
        if not user_input:
            raise ValueError("Empty input. Please enter at least one number.")

        # Check if the input contains commas and at least two numbers
        if "," not in user_input or len(user_input.split(",")) < 2:
            raise ValueError("Numbers should be separated by commas, and you must enter at least two numbers.")

        # Convert input string to a list of floats
        numbers = [float(num) for num in user_input.split(",")]

        if operation == 1:
            # Calculate sum
            result = calculate_sum(numbers)
            print(f"The sum of the numbers is: {result:.2f}")

        elif operation == 2:
            # Calculate average
            result = calculate_average(numbers)
            print(f"The average of the numbers is: {result:.2f}")

        elif operation == 3:
            # Find maximum
            result = find_maximum(numbers)
            print(f"The maximum number is: {result:.2f}")

        elif operation == 4:
            # Find minimum
            result = find_minimum(numbers)
            print(f"The minimum number is: {result:.2f}")

    except ValueError as e:
        # Handle invalid input (non-numeric values or empty lists)
        print(f"Error: {e}. Please enter valid numbers.")


if __name__ == "__main__":
    main()

Welcome to the Math Operations Program!
Please select an operation:
1. Sum
2. Average
3. Maximum
4. Minimum
Enter the number corresponding to your choice: 3
Enter a list of numbers separated by commas: 1,2,3,6,4,8,9
The maximum number is: 9.00



# **4.2 Exercise on List Manipulation:**
1. Extract Every Other Element:
Write a Python function that extracts every other element from a list, starting from the first element.
• Requirements:
– Define a function extract every other(lst) that takes a list lst as input and returns a
new list containing every other element from the original list.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
# 1. Extract Every Other Element
lst = [1, 2, 3, 4, 5, 6]
result = lst[::2]  # Extract every other element starting from the first
print(result)

[1, 3, 5]


# 2. Slice a Sublist:
Write a Python function that returns a sublist from a given list, starting from a specified index and
ending at another specified index.
• Requirements:
– Define a function get sublist(lst, start, end) that takes a list lst, a starting index
start, and an ending index end as input and returns the sublist from start to end (inclusive).
– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should
be [3, 4, 5].

In [ ]:
lst = [1, 2, 3, 4, 5, 6]
start = 2
end = 4
result = lst[start:end+1]  # Slice from start to end (inclusive)
print(result)

[3, 4, 5]


# 3. Reverse a List Using Slicing:
Write a Python function that reverses a list using slicing.
• Requirements:
– Define a function reverse list(lst) that takes a list lst and returns a reversed list using
slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].

In [ ]:
lst = [1, 2, 3, 4, 5]
result = lst[::-1]  # Reverse the list using slicing
print(result)

[5, 4, 3, 2, 1]


# 4. Remove the First and Last Elements:
Write a Python function that removes the first and last elements of a list and returns the resulting
sublist.
• Requirements:
– Define a function remove first last(lst) that takes a list lst and returns a sublist without
the first and last elements using slicing.
– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
lst = [1, 2, 3, 4, 5]
result = lst[1:-1]  # Remove the first and last elements
print(result)


[2, 3, 4]


# 5. Get the First n Elements:
Write a Python function that extracts the first n elements from a list.
• Requirements:
– Define a function get first n(lst, n) that takes a list lst and an integer n as input and
returns the first n elements of the list using slicing.
– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
lst = [1, 2, 3, 4, 5]
n = 3
result = lst[:n]  # Get the first n elements
print(result)

[1, 2, 3]


# 6. Extract Elements from the End:
Write a Python function that extracts the last n elements of a list using slicing.
• Requirements:
– Define a function get last n(lst, n) that takes a list lst and an integer n as input and
returns the last n elements of the list.
– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
lst = [1, 2, 3, 4, 5]
n = 2
result = lst[-n:]  # Get the last n elements
print(result)

[4, 5]


# 7. Extract Elements in Reverse Order:
Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.
• Requirements:
– Define a function reverse skip(lst) that takes a list lst and returns a new list containing
every second element starting from the second-to-last, moving backward.
– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
lst = [1, 2, 3, 4, 5, 6]
result = lst[-2::-2]  # Extract every second element starting from the second-to-last
print(result)


[5, 3, 1]


# 4.3 Exercise on Nested List:
1. Flatten a Nested List:
Write a Python function that takes a nested list and flattens it into a single list, where all the elements
are in a single dimension.
• Requirements:
– Define a function flatten(lst) that takes a nested list lst and returns a flattened version
of the list.
– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
nested_lst = [[1, 2], [3, 4], [5]]
flat_list = [item for sublist in nested_lst for item in sublist]  # Flatten the list
print(flat_list)

[1, 2, 3, 4, 5]


# 2. Accessing Nested List Elements:
Write a Python function that extracts a specific element from a nested list given its indices.
• Requirements:
– Define a function access nested element(lst, indices) that takes a nested list lst and
a list of indices indices, and returns the element at that position.
– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,
2], the output should be 6.

In [ ]:
nested_lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = nested_lst[indices[0]][indices[1]]  # Access the element at the given indices
print(result)

6


# 3. Sum of All Elements in a Nested List:
Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).
• Requirements:
– Define a function sum nested(lst) that takes a nested list lst and returns the sum of all
the elements.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
nested_lst = [[1, 2], [3, [4, 5]], 6]

# Recursive function to flatten the list
def flatten_list(nested_lst):
    flat_list = []
    for item in nested_lst:
        if isinstance(item, list):
            flat_list.extend(flatten_list(item))  # Recursively flatten nested lists
        else:
            flat_list.append(item)  # Add non-list items directly
    return flat_list

# Flatten the list
flat_list = flatten_list(nested_lst)

# Sum all elements
total = sum(flat_list)
print(total)  # Output: 21

21


# 4. Remove Specific Element from a Nested List:
Write a Python function that removes all occurrences of a specific element from a nested list.
• Requirements:
– Define a function remove element(lst, elem) that removes elem from lst and returns the
modified list.
– Example: For the input lst = [[1, 2], [3, 2], [4, 5]] and elem = 2, the output should
be [[1], [3], [4, 5]].

In [ ]:
nested_lst = [[1, 2], [3, 2], [4, 5]]
elem = 2
# Remove all occurrences of `elem`
result = [[item for item in sublist if item != elem] for sublist in nested_lst]
print(result)


[[1], [3], [4, 5]]


# 5. Find the Maximum Element in a Nested List:
Write a Python function that finds the maximum element in a nested list (regardless of depth).
• Requirements:
– Define a function find max(lst) that takes a nested list lst and returns the maximum
element.
– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
nested_lst = [[1, 2], [3, [4, 5]], 6]

# Recursive function to flatten the list
def flatten_list(nested_lst):
    flat_list = []
    for item in nested_lst:
        if isinstance(item, list):
            flat_list.extend(flatten_list(item))  # Recursively flatten nested lists
        else:
            flat_list.append(item)  # Add non-list items directly
    return flat_list

# Flatten the list
flat_list = flatten_list(nested_lst)

# Find the maximum element
max_val = max(flat_list)
print(max_val)  # Output: 6

6


# 6. Count Occurrences of an Element in a Nested List:
Write a Python function that counts how many times a specific element appears in a nested list.
• Requirements:
– Define a function count occurrences(lst, elem) that counts the occurrences of elem in
the nested list lst.
– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2, the output should
be 3.

In [ ]:
nested_lst = [[1, 2], [2, 3], [2, 4]]
elem = 2
# Flatten the list first
flat_list = [item for sublist in nested_lst for item in sublist]
count = flat_list.count(elem)  # Count occurrences of `elem`
print(count)

3


# 7. Flatten a List of Lists of Lists:
Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.
• Requirements:
– Define a function deep flatten(lst) that takes a deeply nested list lst and returns a single
flattened list.
– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be
[1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
deep_nested_lst = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
# Flatten the deeply nested list
flat_list = [item for sublist in deep_nested_lst for subsublist in sublist for item in subsublist]
print(flat_list)

[1, 2, 3, 4, 5, 6, 7, 8]


# 8. Nested List Average:
Write a Python function that calculates the average of all elements in a nested list.
• Requirements:
– Define a function average nested(lst) that takes a nested list lst and returns the average
of all the elements.
– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
nested_lst = [[1, 2], [3, 4], [5, 6]]
# Flatten the list first
flat_list = [item for sublist in nested_lst for item in sublist]
average = sum(flat_list) / len(flat_list)  # Calculate the average
print(average)

3.5


# 10 To - Do - NumPy
Please complete all the problems listed below:
10.1 Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_array)

# 2. Initialize an all ones array with size 4x2
ones_array = np.ones((4, 2))
print("\n2. All ones 4x2 array:\n", ones_array)

# 3. Return a new array of given shape and type, filled with fill value
fill_value_array = np.full((3, 3), 5)  # Shape: 3x3, Fill value: 5
print("\n3. Array filled with value 5:\n", fill_value_array)

# 4. Return a new array of zeros with same shape and type as a given array
zeros_like_array = np.zeros_like(fill_value_array)
print("\n4. Zeros array with same shape as fill_value_array:\n", zeros_like_array)

# 5. Return a new array of ones with same shape and type as a given array
ones_like_array = np.ones_like(fill_value_array)
print("\n5. Ones array with same shape as fill_value_array:\n", ones_like_array)

# 6. Convert a list to a NumPy array
new_list = [1, 2, 3, 4]
numpy_array = np.array(new_list)
print("\n6. Converted NumPy array from list:\n", numpy_array)

1. Empty 2x2 array:
 [[2.42101010e-316 0.00000000e+000]
 [3.69320059e-306 1.75752732e+159]]

2. All ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with value 5:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]

4. Zeros array with same shape as fill_value_array:
 [[0 0 0]
 [0 0 0]
 [0 0 0]]

5. Ones array with same shape as fill_value_array:
 [[1 1 1]
 [1 1 1]
 [1 1 1]]

6. Converted NumPy array from list:
 [1 2 3 4]


# Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
# 1. Create an array with values ranging from 10 to 49
range_array = np.arange(10, 50)
print("\n1. Array with values from 10 to 49:\n", range_array)

# 2. Create a 3x3 matrix with values ranging from 0 to 8
reshaped_array = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix with values 0 to 8:\n", reshaped_array)

# 3. Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity_matrix)

# 4. Create a random array of size 30 and find the mean
random_array = np.random.random(30)
mean_value = random_array.mean()
print("\n4. Random array of size 30:\n", random_array)
print("Mean of the array:", mean_value)

# 5. Create a 10x10 array with random values and find min and max
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("\n5. 10x10 random array:\n", random_10x10)
print("Min value:", min_value)
print("Max value:", max_value)

# 6. Create a zero array of size 10 and replace the 5th element with 1
zero_array = np.zeros(10)
zero_array[4] = 1  # Indexing starts from 0
print("\n6. Zero array with 5th element replaced by 1:\n", zero_array)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_array = arr[::-1]
print("\n7. Reversed array:\n", reversed_array)

# 8. Create a 2D array with 1 on the border and 0 inside
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D array with 1 on border and 0 inside:\n", border_array)

# 9. Create an 8x8 checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. 8x8 checkerboard pattern:\n", checkerboard)


1. Array with values from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix with values 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Random array of size 30:
 [0.87889441 0.06876494 0.42403324 0.72650994 0.96929404 0.67112107
 0.66681448 0.55406199 0.12519662 0.12805458 0.06320426 0.73046113
 0.97153743 0.05540855 0.11216611 0.62748847 0.58770656 0.27826669
 0.19900821 0.0282189  0.27979825 0.2795384  0.09187294 0.546972
 0.23021818 0.78431854 0.52563744 0.79772161 0.32154903 0.8565367 ]
Mean of the array: 0.4526791567099355

5. 10x10 random array:
 [[0.42052174 0.85216932 0.81293718 0.00426393 0.28694596 0.54920465
  0.63972501 0.37066244 0.77310425 0.98804461]
 [0.1192123  0.20159735 0.74043829 0.72060664 0.94280746 0.4475904
  0.55213467 0.45504344 0.86802022 0.13020684]
 [0.74793423 0.9282786  0.50718279 0.84337248 0.621772  

# Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?
Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
# Define arrays
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add the two arrays
add_result = x + y
print("\n1. Addition of x and y:\n", add_result)

# 2. Subtract the two arrays
subtract_result = x - y
print("\n2. Subtraction of x and y:\n", subtract_result)

# 3. Multiply the array with an integer
multiply_result = x * 2
print("\n3. Multiplication of x by 2:\n", multiply_result)

# 4. Find the square of each element
square_result = np.square(x)
print("\n4. Square of each element in x:\n", square_result)

# 5. Find the dot product
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n5. Dot products:")
print("v and w:", dot_vw)
print("x and v:", dot_xv)
print("x and y:\n", dot_xy)

# 6. Concatenate x and y along rows, and v and w along columns
concat_rows = np.vstack((x, y))
concat_cols = np.hstack((v[:, np.newaxis], w[:, np.newaxis]))
print("\n6. Concatenation:")
print("x and y along rows:\n", concat_rows)
print("v and w along columns:\n", concat_cols)

# 7. Concatenate x and v (will raise an error)
try:
    np.concatenate((x, v))
except ValueError as e:
    print("\n7. Error when concatenating x and v:", e)
    print("Explanation: Shapes of x (2x2) and v (2,) are not compatible for concatenation.")


1. Addition of x and y:
 [[ 6  8]
 [10 13]]

2. Subtraction of x and y:
 [[-4 -4]
 [-4 -3]]

3. Multiplication of x by 2:
 [[ 2  4]
 [ 6 10]]

4. Square of each element in x:
 [[ 1  4]
 [ 9 25]]

5. Dot products:
v and w: 219
x and v: [29 77]
x and y:
 [[19 22]
 [50 58]]

6. Concatenation:
x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
v and w along columns:
 [[ 9 11]
 [10 12]]

7. Error when concatenating x and v: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Shapes of x (2x2) and v (2,) are not compatible for concatenation.


# Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)

T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” func-
tion of Numpy}

In [ ]:
# Define matrices
A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^(-1) = I
A_inv = np.linalg.inv(A)
identity_check = np.dot(A, A_inv)
print("\n1. A.A^(-1):\n", identity_check)

# 2. Prove AB != BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB:\n", AB)
print("BA:\n", BA)
print("AB != BA:", not np.array_equal(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_transpose = AB.T
B_transpose_A_transpose = np.dot(B.T, A.T)
print("\n3. (AB)^T:\n", AB_transpose)
print("B^T A^T:\n", B_transpose_A_transpose)
print("(AB)^T == B^T A^T:", np.array_equal(AB_transpose, B_transpose_A_transpose))

# Solve the system of linear equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9
coefficients = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])
solution = np.linalg.inv(coefficients).dot(constants)
print("\nSolution to the system of equations:", solution)


1. A.A^(-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]

2. AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
AB != BA: True

3. (AB)^T:
 [[23 51]
 [13 29]]
B^T A^T:
 [[23 51]
 [13 29]]
(AB)^T == B^T A^T: True

Solution to the system of equations: [ 2.  1. -2.]


# 10.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
2. Element-wise Multiplication
• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000.
Measure and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.
4. Matrix Multiplication

• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000.
Measure and print the time taken for this operation.

In [ ]:
import time

# Element-wise addition
size = 1000000
python_list1 = list(range(size))
python_list2 = list(range(size))

start_time = time.time()
result = [a + b for a, b in zip(python_list1, python_list2)]
python_time = time.time() - start_time
print("\nPython list addition time:", python_time)

numpy_array1 = np.arange(size)
numpy_array2 = np.arange(size)

start_time = time.time()
result = numpy_array1 + numpy_array2
numpy_time = time.time() - start_time
print("NumPy array addition time:", numpy_time)

# Repeat for multiplication and dot product


Python list addition time: 0.0815286636352539
NumPy array addition time: 0.024537086486816406
